name: pdf2bitmap
description: "A Flutter plugin that converts PDF files to high-quality bitmap images on Android devices."
version: 0.0.2
homepage: https://github.com/eq-devs/pdf2bitmap

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eq.pdf2bitmap
        pluginClass: Pdf2bitmapPlugin